// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqi_LHH1IFQN5nlC8n_nKRUCQsVV3_xR8',
    appId: '1:1035038539502:ios:42f321d57f0217c18abdff',
    messagingSenderId: '1035038539502',
    projectId: 'mis-lab3-47764',
    storageBucket: 'mis-lab3-47764.firebasestorage.app',
    iosBundleId: 'com.example.newFlutterProject',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTMYYeKbRuoW8zaDtpHA92PMSJshUAssg',
    appId: '1:1035038539502:android:3377a77b7b26d11d8abdff',
    messagingSenderId: '1035038539502',
    projectId: 'mis-lab3-47764',
    storageBucket: 'mis-lab3-47764.firebasestorage.app',
  );

}